Repository FinnHuelsbusch/tutorensystem, pull requests merged in 2022-02, with the labels that each got.

#1 Added Setupguide fot the project
  Setup.md
Labels: documentation

#3 Main
  backend/.devcontainer.json
  docker-dompose.backend.yml
  docker-dompose.frontend.yml
Labels: enhancement

#2 Updated springdoc to latest
  backend/pom.xml
Labels: enhancement

#6 Merge pull request #4 from FinnHuelsbusch:feat/addLombok
  frontend/src/index.tsx
Labels: bug

#8 Feat/docker-data
  backend/.gitignore
Labels: enhancement

#10 Feat/initial setup frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/adminOverview/AdminOverview.tsx
  frontend/src/components/directorOverview/DirectorOverview.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/overview/Overview.tsx
  frontend/src/components/routes/ProtectedRoute.tsx
  frontend/src/components/routes/Unauthorized.tsx
  frontend/src/types/User.tsx
Labels: enhancement

#11 Feat/security
  backend/src/main/resources/application.properties.db
  backend/src/main/resources/application.properties.docker
Labels: enhancement
